---
title: "cleaning dataset 2"
output: html_document
---

<<<<<<< HEAD
``` 
=======
```
>>>>>>> 5fa94ee5484706ab018943394f93cb0611145331
IPEDS_data$`Religious affiliation`<- NULL
IPEDS_data$`Highest degree offered`<- NULL
IPEDS_data$`Offers Less than one year certificate`<- NULL
IPEDS_data$`Offers One but less than two years certificate` <- NULL
IPEDS_data$`Offers Associate's degree`<- NULL
IPEDS_data$`Offers Bachelor's degree`<- NULL
IPEDS_data$`Offers Two but less than 4 years certificate`<- NULL
IPEDS_data$`Offers Postbaccalaureate certificate`<- NULL
IPEDS_data$`Offers Master's degree`<- NULL
IPEDS_data$`Offers Post-master's certificate <- NULL
IPEDS_data$`Offers Doctor's degree - research/scholarship` <- NULL
IPEDS_data$`Offers Doctor's degree - professional practice`<- NULL
IPEDS_data$`Offers Doctor's degree - other`<- NULL
IPEDS_data$`Offers Post-master's certificate`<- NULL
IPEDS_data$`Offers Doctor's degree - research/scholarship`<- NULL
IPEDS_data$`Offers Other degree`<- NULL
IPEDS_data$`Percent of freshmen submitting ACT scores`<- NULL
IPEDS_data$`ACT Composite 25th percentile score`<- NULL
IPEDS_data$`ACT Composite 75th percentile score`<- NULL
IPEDS_data$`Estimated enrollment, full time`<- NULL
IPEDS_data$`Estimated enrollment, part time`<- NULL
IPEDS_data$`Estimated enrollment, total`<- NULL
IPEDS_data$`Estimated freshman enrollment, full time`<- NULL
IPEDS_data$`Estimated freshman enrollment, part time`<- NULL
IPEDS_data$`Estimated freshman undergraduate enrollment, total`<- NULL
IPEDS_data$`Estimated graduate enrollment, full time`<- NULL
IPEDS_data$`Estimated graduate enrollment, part time`<- NULL
IPEDS_data$`Estimated graduate enrollment, total`<- NULL
IPEDS_data$`Estimated undergraduate enrollment, full time`<- NULL 
IPEDS_data$`Estimated undergraduate enrollment, part time`<- NULL
IPEDS_data$`Estimated undergraduate enrollment, total`<- NULL
IPEDS_data$`Associate's degrees awarded`<- NULL
IPEDS_data$`Bachelor's degrees awarded`<- NULL
IPEDS_data$`Master's degrees awarded`<- NULL
IPEDS_data$`Endowment assets (year end) per FTE enrollment (FASB)`<- NULL
IPEDS_data$`Endowment assets (year end) per FTE enrollment (GASB)`<- NULL
IPEDS_data$`Percent of freshmen receiving other loan aid`<- NULL
IPEDS_data$`Percent of freshmen receiving federal student loans`<- NULL
IPEDS_data$`Percent of freshmen receiving student loan aid`<- NULL
IPEDS_data$`Percent of freshmen receiving institutional grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving state/local grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving other federal grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving Pell grants`<- NULL
IPEDS_data$`Percent of freshmen receiving federal grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving federal grant aid`<- NULL
IPEDS_data$`Doctor's degrees - other awarded`<- NULL
IPEDS_data$`Doctor's degrees - professional practice awarded`<- NULL
IPEDS_data$`Doctor's degrese - research/scholarship awarded`<- NULL
IPEDS_data$`Certificates of 1 but less than 2-years awarded`<- NULL 
IPEDS_data$`Certificates of 2 but less than 4-years awarded`<- NULL
IPEDS_data$`Certificates of less than 1-year awarded`<- NULL
IPEDS_data$`Postbaccalaureate certificates awarded`<- NULL
IPEDS_data$`Post-master's certificates awarded`<- NULL 
IPEDS_data$`Number of first-time undergraduates - foreign countries`<- NULL
IPEDS_data$`Number of first-time undergraduates - in-state`<- NULL
IPEDS_data$`Number of students receiving an Associate's degree`<- NULL
IPEDS_data$`Number of students receiving a Bachelor's degree`<- NULL
IPEDS_data$`Number of students receiving a Master's degree`<- NULL
IPEDS_data$`Number of students receiving a certificate of less than 1-year`<- NULL
IPEDS_data$`Number of students receiving a Doctor's degree`<- NULL 
IPEDS_data$`Number of students receiving a certificate of 1 but less than 4-years`<- NULL
IPEDS_data$`Number of students receiving a Postbaccalaureate or Post-master's certificate`<- NULL
IPEDS_data$`Tuition and fees, 2010-11`<- NULL 
IPEDS_data$`Tuition and fees, 2011-12`<- NULL
IPEDS_data$`Tuition and fees, 2012-13`<- NULL
IPEDS_data$`Tuition and fees, 2013-14`<- NULL
IPEDS_data$`Endowment assets (year end) per FTE enrollment (FASB)`<- NULL
IPEDS_data$`Endowment assets (year end) per FTE enrollment (GASB)`<- NULL
IPEDS_data$`Percent of freshmen receiving other loan aid`<- NULL
IPEDS_data$`Percent of freshmen receiving federal student loans`<- NULL
IPEDS_data$`Percent of freshmen receiving student loan aid`<- NULL
IPEDS_data$`Percent of freshmen receiving institutional grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving state/local grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving other federal grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving Pell grants`<- NULL
IPEDS_data$`Percent of freshmen receiving  federal grant aid` <- NULL
IPEDS_data$`Percent of freshmen receiving federal, state, local or institutional grant aid` <- NULL
IPEDS_data$`Percent of freshmen receiving any financial aid` <- NULL
IPEDS_data$`Graduation rate - Bachelor degree within 5 years, total` <- NULL
IPEDS_data$`Graduation rate - Bachelor degree within 6 years, total`<- NULL
IPEDS_data$`Number of first-time undergraduates - in-state` <- NULL
IPEDS_data$`Percent of first-time undergraduates - residence unknown` <- NULL
IPEDS_data$`Total price for in-state students living on campus 2013-14`<- NULL
IPEDS_data$`Total price for out-of-state students living on campus 2013-14`<- NULL
IPEDS_data$`State abbreviation`<- NULL
IPEDS_data$`FIPS state code`<- NULL
IPEDS_data$`Geographic region`<- NULL
IPEDS_data$`Sector of institution`<- NULL
IPEDS_data$`Level of institution`<- NULL
IPEDS_data$`Control of institution`<- NULL
IPEDS_data$`Historically Black College or University`<- NULL
IPEDS_data$`Degree of urbanization (Urban-centric locale)`<- NULL
IPEDS_data$`Carnegie Classification 2010: Basic`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Black or African American`<- NULL
IPEDS_data$`Percent of graduate enrollment that are American Indian or Alaska Native`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Asian`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Asian/Native Hawaiian/Pacific Islander`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Hispanic/Latino`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Native Hawaiian or Other Pacific Islander`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Nonresident Alien`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Race/ethnicity unknown`<- NULL
IPEDS_data$`Percent of graduate enrollment that are White`<- NULL
IPEDS_data$`Percent of total enrollment that are American Indian or Alaska Native`<-NULL
IPEDS_data$`Percent of total enrollment that are Black or African American`<- NULL
IPEDS_data$`Percent of total enrollment that are White`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Hispanic/Latino`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Black or African American`<- NULL
IPEDS_data$`Percent of total enrollment that are Native Hawaiian or Other Pacific Islander`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are American Indian or Alaska Native`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander`< NULL
IPEDS_data$`Percent of undergraduate enrollment that are Asian`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Native Hawaiian or Other Pacific Islander`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are White`<- NULL
IPEDS_data$`Percent of total enrollment that are Asian`<- NULL
IPEDS_data$`Percent of total enrollment that are Asian/Native Hawaiian/Pacific Islander`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander`<- NULL
IPEDS_data$`Percent of total enrollment that are Hispanic/Latino`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Nonresident Alien`<- NULL
IPEDS_data$`Percent of total enrollment that are Nonresident Alien`<- NULL




















































End of Zoe's cleaning

``

 

IPEDS_data$`Endowment assets (year end) per FTE enrollment (FASB)`<- NULL
IPEDS_data$`Endowment assets (year end) per FTE enrollment (GASB)`<- NULL
IPEDS_data$`Percent of freshmen receiving other loan aid`<- NULL
IPEDS_data$`Percent of freshmen receiving federal student loans`<- NULL
IPEDS_data$`Percent of freshmen receiving student loan aid`<- NULL
IPEDS_data$`Percent of freshmen receiving institutional grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving state/local grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving other federal grant aid`<- NULL
IPEDS_data$`Percent of freshmen receiving Pell grants`<- NULL
IPEDS_data$`Percent of freshmen receiving  federal grant aid` <- NULL
IPEDS_data$`Percent of freshmen receiving federal, state, local or institutional grant aid` <- NULL
IPEDS_data$`Percent of freshmen receiving any financial aid` <- NULL
IPEDS_data$`Graduation rate - Bachelor degree within 5 years, total` <- NULL
IPEDS_data$`Graduation rate - Bachelor degree within 6 years, total`<- NULL
IPEDS_data$`Number of first-time undergraduates - in-state` <- NULL
IPEDS_data$`Percent of first-time undergraduates - residence unknown` <- NULL
IPEDS_data$`Number of first-time undergraduates - residence unknown`<- NULL
IPEDS_data$`Percent of first-time undergraduates - out-of-state`<- NULL
IPEDS_data$`Percent of first-time undergraduates - foreign countries`<- NULL
IPEDS_data$`Number of first-time undergraduates - out-of-state` <- NULL
IPEDS_data$`Percent of first-time undergraduates - in-state`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Race/ethnicity unknown`<- NULL
IPEDS_data$`Percent of graduate enrollment that are women`<-NULL
IPEDS_data$`Percent of graduate enrollment that are Asian/Native Hawaiian/Pacific Islander` <-NULL
IPEDS_data$`Percent of graduate enrollment that are two or more races`<- NULL
IPEDS_data$`Percent of graduate enrollment that are White`<-NULL
IPEDS_data$`Percent of graduate enrollment that are Nonresident Alien` <- NULL
IPEDS_data$`Percent of graduate enrollment that are Native Hawaiian or Other Pacific Islander`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Hispanic/Latino`<-NULL
IPEDS_data$`Percent of graduate enrollment that are Black or African American`<- NULL
IPEDS_data$`Percent of graduate enrollment that are Asian`<-NULL
IPEDS_data$`Percent of graduate enrollment that are American Indian or Alaska Native`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are women`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander` <- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Nonresident Alien`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Race/ethnicity unknown`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are two or more races`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are White`<- NULL
IPEDS_data$`Percent of undergraduate enrollment that are Hispanic/Latino`<-NULL
IPEDS_data$`Percent of undergraduate enrollment that are Native Hawaiian or Other Pacific Islander`<-NULL
IPEDS_data$`Percent of undergraduate enrollment that are Black or African American`<- NULL