---
title: "Search-by-college-df"
output: html_document
---

```{r setup, include=FALSE}

head(IPEDS_data)
library(leaflet)

```


```{r setup, include=FALSE}

search_by_df <- data.frame(IPEDS_data$Name, 
                           IPEDS_data$`Applicants total`, 
                           IPEDS_data$`Admissions total`,
                           IPEDS_data$`Admissions yield - total`,
                           IPEDS_data$`SAT Critical Reading 25th percentile score`, 
                           IPEDS_data$`SAT Critical Reading 75th percentile score`, 
                           IPEDS_data$`SAT Math 25th percentile score`, 
                           IPEDS_data$`SAT Math 75th percentile score`, 
                           IPEDS_data$`SAT Writing 25th percentile score`,
                           IPEDS_data$`SAT Writing 75th percentile score`
                          )

```

```{r}
search_by_df <- IPEDS_data_2[, c(2, 8, 9, 19, 12:17)]

```

```{r}
search_by_stats <- IPEDS_data_2$`Total SAT 25th Percentile`
```

```{r}
as.numeric(IPEDS_data_2$`Longitude location of institution`)

as.numeric(IPEDS_data_2$`Latitude location of institution`)

as.list(IPEDS_data_2$Name)
```

```{r}
IPEDS_data_2 %>%
        filter(Name = "Amherst College") %>% 
        leaflet() %>% 
        setView(lng = as.numeric(IPEDS_data_2$`Longitude location of institution`), 
                lat = as.numeric(IPEDS_data_2$`Latitude location of institution`), 
                zoom = 12) %>% 
        addTiles()
```


```{r}
IPEDS_data_2 %>%
        filter(Name == "Amherst College") %>% 
        leaflet() %>% 
        setView(lng = -72.519333, 
                lat = 42.372139, 
                zoom = 12) %>% 
        addTiles()
```
```{r}
leaflet(data = IPEDS_data_2) %>%
  filter(IPEDS_data_2$Name = 'University of Alabama') %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap) %>%
  setView(lng = as.numeric(IPEDS_data_2$`Longitude location of institution`), 
          lat = as.numeric(IPEDS_data_2$`Latitude location of institution`), 
          zoom = 12) %>%
  addMarkers(label = IPEDS_data_2$Name)
  
```


```{r}
library(ggplot2)
View(diamonds)
```

```{r}
IPEDS_data %>% 
  filter(IPEDS_data$`State abbreviation` == "Alabama") %>%
  ggplot(aes(IPEDS_data$`Estimated freshman enrollment, full time`, IPEDS_data$`Tuition and fees, 2013-14`)) +
    geom_point()
```

```{r}
 ggplot(IPEDS_data_2, aes(IPEDS_data_2$`SAT Math 25th percentile score`, IPEDS_data_2$`Tuition and fees, 2013-14`)) +
    geom_point()
```

